kind: Service
apiVersion: v1
metadata:
  name: {{.Values.service.name}} 
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{.Values.service.name}}
    visualize: "true" 
spec:
  ports: 
    - port: 80
#      name: # The name of this port within the service. Optional if only one port is defined on this service
      targetPort: 80
  selector: 
    app: {{ .Values.service.name }} 
